import React, { useState } from 'react';
import { api } from '../utils/api';
import { formatCurrency } from '../utils/format';

export default function ExecutiveSummary({ rollup }) {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);

  const generateSummary = async () => {
    setLoading(true);
    try {
      const result = await api.getExecutiveSummary();
      setSummary(result);
    } catch (err) {
      console.error('Failed to generate summary:', err);
    } finally {
      setLoading(false);
    }
  };

  const exportMarkdown = () => {
    if (!summary) return;
    const content = `# Global Workforce Optimization — Executive Report\n\n**Generated:** ${new Date().toLocaleDateString()}\n\n---\n\n## Key Metrics\n\n| Metric | Value |\n|--------|-------|\n| Total FTE | ${summary.metrics.totalFTE} |\n| Total Annual Spend | ${formatCurrency(summary.metrics.totalSpend)} |\n| Offshore-Ready FTE | ${summary.metrics.offshoreFTE} (${summary.metrics.offshorePercent}%) |\n| Estimated Annual Savings | ${formatCurrency(summary.metrics.estimatedSavings)} |\n| Quality Risk Score | ${summary.metrics.qualityRiskScore}/100 |\n\n---\n\n## Executive Summary\n\n${summary.summary}\n\n---\n\n*Generated by GWOE — Global Workforce Optimization Engine*\n`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `GWOE_Executive_Report_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="card p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl font-semibold text-white">Summary for C-Suite</h2>
            <p className="text-sm text-gwoe-muted mt-1">AI-generated executive briefing on workforce optimization findings</p>
          </div>
          <div className="flex gap-2">
            <button onClick={generateSummary} disabled={loading} className="btn-primary">
              {loading ? 'Generating...' : summary ? 'Regenerate' : 'Generate Report'}
            </button>
            {summary && (
              <button onClick={exportMarkdown} className="btn-secondary">
                Export Deck
              </button>
            )}
          </div>
        </div>

        {!summary && !loading && (
          <div className="text-center py-16 text-gwoe-muted">
            <p className="text-4xl mb-4">📊</p>
            <p className="text-sm">Click "Generate Report" to create an AI-powered executive summary</p>
            <p className="text-xs mt-1">Analyzes all business units and generates a 300-word C-Suite briefing</p>
          </div>
        )}

        {loading && (
          <div className="text-center py-16">
            <div className="w-10 h-10 border-2 border-gwoe-accent border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-sm text-gwoe-muted">AI is analyzing all business units...</p>
          </div>
        )}

        {summary && (
          <div className="space-y-6">
            {/* Key Metrics */}
            <div className="grid grid-cols-5 gap-3">
              <div className="bg-gwoe-bg rounded-lg p-4">
                <p className="text-xs text-gwoe-muted">Total FTE</p>
                <p className="text-xl font-bold text-white mt-1">{summary.metrics.totalFTE}</p>
              </div>
              <div className="bg-gwoe-bg rounded-lg p-4">
                <p className="text-xs text-gwoe-muted">Annual Spend</p>
                <p className="text-xl font-bold text-white mt-1">{formatCurrency(summary.metrics.totalSpend)}</p>
              </div>
              <div className="bg-gwoe-bg rounded-lg p-4">
                <p className="text-xs text-gwoe-green">Offshore FTE</p>
                <p className="text-xl font-bold text-gwoe-green mt-1">{summary.metrics.offshoreFTE}</p>
              </div>
              <div className="bg-gwoe-bg rounded-lg p-4">
                <p className="text-xs text-gwoe-green">Est. Savings</p>
                <p className="text-xl font-bold text-gwoe-green mt-1">{formatCurrency(summary.metrics.estimatedSavings)}</p>
              </div>
              <div className="bg-gwoe-bg rounded-lg p-4">
                <p className="text-xs text-gwoe-amber">Risk Score</p>
                <p className="text-xl font-bold text-gwoe-amber mt-1">{summary.metrics.qualityRiskScore}/100</p>
              </div>
            </div>

            {/* Executive Summary Text */}
            <div className="bg-gwoe-bg rounded-lg p-6 border border-gwoe-border">
              <div className="prose prose-sm prose-invert max-w-none">
                {summary.summary.split('\n\n').map((paragraph, i) => (
                  <p key={i} className="text-sm text-gwoe-text leading-relaxed mb-3 last:mb-0">
                    {paragraph}
                  </p>
                ))}
              </div>
            </div>

            <div className="flex items-center justify-between text-xs text-gwoe-muted pt-2 border-t border-gwoe-border">
              <span>Generated by GWOE AI Engine — {new Date().toLocaleString()}</span>
              <span>Confidence: High — Based on {summary.metrics.totalFTE} FTE across {rollup?.byUnit?.length || 6} units</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
